### ISSUE TITLE
JobHash of event result in BidCreated is invalid 

### ISSUE THREAD

**Issue by hieuht2048** [bigbomio/bigbom-marketplace#10]
**Describe the bug**
Call the BidCreated to get Bid event, but result include jobHash invalid

**Screenshots**
[![Screenshot from Gyazo](https://gyazo.com/bdb6541570e28dd3f4a72780bb79d993/raw)](https://gyazo.com/bdb6541570e28dd3f4a72780bb79d993)

**Comment by chris-tn** [comment]
the jobHash from BidCreated event has been encrypted by sha3, so please use web3.sha3(jobhash) for jobHash input parameter to filter by jobHash

Thank you
