### ISSUE TITLE
Wrong job budget displaying

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#12]
**Describe the bug**
Job budget in Manage view and detail view is different

**To Reproduce**
1. Post a job. Select any budget, "Small Budget" for example
2. Waiting for the job being created
3. Go to Manage view, check the Job Budget amount
4. Click to the Job, check the Job Budget amount

**Expected behavior**
Those 2 amount should be the same

**Screenshots**
Manage View:
<img width="1116" alt="screen shot 2018-08-27 at 4 13 54 pm" src="https://user-images.githubusercontent.com/1546109/44651884-ad65d500-aa14-11e8-9304-28caf2afa47a.png">
Detail View:
<img width="1119" alt="screen shot 2018-08-27 at 4 14 10 pm" src="https://user-images.githubusercontent.com/1546109/44651905-ba82c400-aa14-11e8-9b51-1c3ae02931ec.png">

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Chrome
 - Version: 68.0.3440.106 (Official Build) (64-bit)

**Comment by hieuht2048** [comment]
Thank for your feedback,
I saved budget data with two value, min_sum and max_sum (by range), because we don't use budget by range, so I have to use max_sum for user select, but I forget use it for display, I use min_sum :D
