### ISSUE TITLE
Temporarily hidden the category selection at home screen

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#23]
Currently we're not having any logic defined for clicking to any categories at home screen. In future release, it should lead to a specific actions or we may completely change the UI. With that reason, we should hide that block in this current release

**Comment by hieuht2048** [comment]
Resolved in 36eac0184f08b7884c1c3d4b80fb0bab752ab1b3

**Comment by onimsha** [comment]
Close in favor of #36
