### ISSUE TITLE
Disabling clicking to Trezor and Ledger for connecting wallet

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#24]
Current release only support Metamask, we should not let people click into Trezor and Ledger for authentication since it will create confusion.

We will re-open this feature in upcoming release

**Comment by hieuht2048** [comment]
Resolved in 36eac0184f08b7884c1c3d4b80fb0bab752ab1b3

**Comment by onimsha** [comment]
Close in favor of #36
