### ISSUE TITLE
Support "Custom" BBO value as budget and remove the dollar sign

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#25]
**Is your feature request related to a problem? Please describe.**
We should let people specify a custom BBO value for the budget, also we need to reduce the list of budget range since i don't think current configuration is optimized

Also the dollar sign `$` is misleading, because we're using BBO as the currency, not fiat.

**Describe the solution you'd like**
We should apply this range for budget selection . 

Name | Value
------ | -----
Small Project | BBO 200,000
Medium Project | BBO 1,000,000
Medium-Large Project | BBO 1,500,000
Large Project | BBO 3,000,000
Very Large Project | BBO 10,000,000
Custom |

**Comment by hieuht2048** [comment]
Resolved in 36eac0184f08b7884c1c3d4b80fb0bab752ab1b3

**Comment by hieuht2048** [comment]
Resolved in 0e021d9477a8ecdba3db5af02a4f03d85158a90b
