### ISSUE TITLE
Better tooltips for the Estimated time and Expired time on job creation screen

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#26]
This is current text explanation for Estimated time and Expired time
<img width="1076" alt="screen shot 2018-09-06 at 9 39 06 am" src="https://user-images.githubusercontent.com/1546109/45131805-c448bc00-b1b8-11e8-9657-3f156f7dfad6.png">

My suggestion for the improvement is

- [] Move the unit next to the input, rather than put it in the tooltips
- [] Change the tooltips of Estimated time to "Time estimated for completing this job"
- [] Change the tooltips of Expired time to "Maximum bid period"

**Comment by hieuht2048** [comment]
Resolved in 36eac0184f08b7884c1c3d4b80fb0bab752ab1b3

**Comment by onimsha** [comment]
Close in favor of #36
