### ISSUE TITLE
Adding shortcut to check transaction history on Etherscan

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#27]
**Is your feature request related to a problem? Please describe.**
After submitting a transaction, user need to open metamask and click to the transaction in order to check it's status on Etherscan. If people is using hardware wallet, then they won't able to check it since they're not connecting via Metamask

**Describe the solution you'd like**
Adding a shortcut on the transaction confirmation screen so people can check the TX on Etherscan after submitting TX. It should diligently support Mainnet/Ropsten/Tomochain block explorer

**Comment by hieuht2048** [comment]
Resolved in 36eac0184f08b7884c1c3d4b80fb0bab752ab1b3, but in this version, only support for Ropsten network

**Comment by onimsha** [comment]
Close in favor of #36
