### ISSUE TITLE
Add "Place new bid" button

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#29]
**Is your feature request related to a problem? Please describe.**
Since we let people to replace their previous bid in contract side, we should allow that from DApp side also

**Describe the solution you'd like**
Adding new button, "Place new bid", allow to submit a new bid, replacing current one
Cancel bid button still the same.

**Comment by hieuht2048** [comment]
Resolved in commit https://github.com/bigbomio/bigbom-marketplace/commit/d9e2fd2803c8e29fe715f7b219e646033b0fc0c0
