### ISSUE TITLE
After confirm an action, it should not allow people to confirm again while Metamask is still opening

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#30]
**Describe the bug**
In some scenarios, like "Bid" or "Cancel Bid", after confirming the action and switching to Metamask for signing the request, these buttons are still available for clicking

**To Reproduce**
1. Place a bid or Cancel a bid
2. Checking the "Waiting pop up on the main screen"

**Expected behavior**
Buttons should not click-able 

**Screenshots**
## Place a bid:
<img width="605" alt="screen shot 2018-09-06 at 4 53 24 pm" src="https://user-images.githubusercontent.com/1546109/45150385-ed3b7200-b1f5-11e8-8649-772f104ca19d.png">

## Cancel a bid:
<img width="603" alt="screen shot 2018-09-06 at 4 54 09 pm" src="https://user-images.githubusercontent.com/1546109/45150406-f75d7080-b1f5-11e8-9166-fb2e3e8531a1.png">

**Comment by hieuht2048** [comment]
Resolved in 36eac0184f08b7884c1c3d4b80fb0bab752ab1b3

**Comment by onimsha** [comment]
Close in favor of #36
