### ISSUE TITLE
Correct the allowance check behavior

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#31]
**Describe the bug**
According to our design, before deposit BBO into contracts, if the current allowance is bigger than the deposit amount, it should not reset the allowance to 0 before setting new allowance. However currently implementation is ignoring the current allowance comparison, resulting to sending 2 transaction for setting the allowance.

**To Reproduce**
1. Accept a bid
2. Check the "Approve" transaction from Metamask. 

**Expected behavior**
It should not require to reset the allowance to 0, if the current allowance is already bigger than the bid amount

**Comment by hieuht2048** [comment]
Resolved in 36eac0184f08b7884c1c3d4b80fb0bab752ab1b3

**Comment by onimsha** [comment]
Close in favor of #36
