### ISSUE TITLE
Check BBO balance before sending transaction

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#33]
Certain actions such as deposit BBO requires that account balance must >= required amount. We should display an error for letting user know that they don't have sufficient balance before actually sending the transaction through Metamask

**Comment by hieuht2048** [comment]
Resolved in 36eac0184f08b7884c1c3d4b80fb0bab752ab1b3

**Comment by onimsha** [comment]
Close in favor of #36
