### ISSUE TITLE
Enhancing the bid filter 

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#40]
Today while checking the "My Bid" screen, i notified that the loading time of this page is significant, and it takes a long time before starting showing my bids. It should not like that since i only placed my bid for 4-5 jobs

Using Developer Console, i figured that dApp is loading a lot of job hashes from IPFS, so i guess that web client is filtering AFTER scanning all the posted jobs.

**To Reproduce**
1. Go to My Bid
2. Open Developer Console
3. Check for the request to https://ipfs.infura.io

**Screenshots**
![screen shot 2018-09-13 at 10 28 02 am](https://user-images.githubusercontent.com/1546109/45465676-6da32b00-b740-11e8-90af-3dfa4087d239.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X High Sierra
 - Browser: Google Chrome 64 bit
 - Version: 69.0.3497.92

**TODO**
What we can do for increasing the loading time for filter "My Bid" ??

**Comment by onimsha** [comment]
Switching to Cloudflare IPFS gateway does reduce the loading time significantly, up to 10x

**Comment by onimsha** [comment]
Fixes by #43

**Comment by hieuht2048** [comment]
Will be enhance after the next building version of contract. 
How to: 
- Filter createdBid in the first
- Use jobHash in event of createdBid to filter jobCreated by jobHash (indexed)
Result: With this way, only get data from IPFS of the filtered jobs.
