### ISSUE TITLE
Proposals for version 0.0.3

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#41]
Today after internal discussion, we came up with a proposal for version 0.0.3. This is subjected to be change at anytime. 

BREAKING CHANGES:
* [UI] Implement a feature to allow switching between Client/Freelancer/Voter role. 
~~* [RPC] Experiment the feature to override the RPC for Metamask to avoid depending to Infura.~~

FEATURES:
* Basic profile support. Allows user to link their Ethereum address with Bigbom's profile. 
* Supports filtering by Ethereum address for compatible with multiple addresses being associated with a single Bigbom's profile
* Supply reason when rejecting payment https://github.com/bigbomio/digital-contracts/issues/64
* Implements Dispute Voting workflow 
* Using IPFS for revealing votes
* Adding "Place new bid" button #29 

ENHANCEMENTS:
* [UI] Moving account balance into profile shortcut
* [UI] Better job/bid sorting #40 
* [UI] Smart countdown for job #22

**Comment by onimsha** [comment]
@hieuht2048  Reject reason is being described here : https://github.com/bigbomio/digital-contracts/issues/64

**Comment by hieuht2048** [comment]
[UI] Implement a feature to allow switching between Client/Freelancer/Voter role. => Resolved in https://github.com/bigbomio/bigbom-marketplace/commit/b9a7f850dd24d08570cc75106920d97a09284719
