### ISSUE TITLE
Unable to create job if "Estimated time" is too big

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#45]
**Describe the bug**
When create a job, if the amount of "Estimated time" is too big, 
**To Reproduce**
1. Login as Client
2. Create a job
3. In the "Estimated Time" input, put a super large number, like `99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999`. Since the input does not validate the amount, we can still submit this job

**Expected behavior**
It should have a maximum duration, like it cannot larger than 1 year.

**Screenshots**
<img width="1090" alt="screen shot 2018-09-19 at 1 41 05 pm" src="https://user-images.githubusercontent.com/1546109/45740876-6ee0c600-bc20-11e8-8b4f-4dc12f58dd6b.png">

**Comment by onimsha** [comment]
kudos to https://github.com/CQBinh for reported this bug

**Comment by hieuht2048** [comment]
Resolved in commit https://github.com/bigbomio/bigbom-marketplace/commit/d9e2fd2803c8e29fe715f7b219e646033b0fc0c0
