### ISSUE TITLE
Fix the text in "My Bid" section

### ISSUE THREAD

**Issue by onimsha** [bigbomio/bigbom-marketplace#46]
Reported by https://github.com/CQBinh

When open the "My Bid" screen, it should says "Your Bids" instead of "Your Jobs" 

Screenshot:
![screen shot 2018-09-19 at 3 36 40 pm](https://user-images.githubusercontent.com/1546109/45741470-d6e3dc00-bc21-11e8-93d8-19573a02ea51.png)

**Comment by hieuht2048** [comment]
Resolved in commit https://github.com/bigbomio/bigbom-marketplace/commit/d9e2fd2803c8e29fe715f7b219e646033b0fc0c0
